New update for 8.11.0.1 Release (#35)
* updated documentation links

* added link to IBM Docs documentation

* added link to IBM Docs documentation

* Update Chart.yaml

* Update values.yaml

* Update default repository to icr.io/odm-k8s (#28)

* issue https://github.com/helm/helm/issues/3810

workaround issue https://github.com/helm/helm/issues/3810 on fyre
Error: chart requires kubeVersion: >=1.11.0 which is incompatible with Kubernetes v1.22.0-rc.0+a44d0f0

* Add 21.3.0 release

* Update doc links for 8.11.0.0

* Change License

* Fix License

* Fix helm chart version to be align to the image name.

* Fix version for 21.3.0 Version

* Update docker pull instruction

* Prepare source code for the 22.0.1 RElease  DBACLD-33052

* Change copyright Year to 2022: DBACLD-33274

* Revert brth date to 2020

* Pyl ghactions (#32)

* Test id

* Try to pass an option to the container

* Check rights

* Removed working-directory

* Download cv and lint Helm chart

* Add debug

* Add GHE_TOKEN from secret

* Test older version of cv

* Fix or ignore errors for cv 2.6.0

* Added ephemeral-storage limits for ConfigMap and removed useless lint overrides

* Added Helm packaging

* Fixed index file name

* Download ODM dist

* Make sure ${HOME}/.cache exists

* Full chain--first try (it won't work)

* Add ODMIMAGEVERSION to job's env

* Moved env declaration

* How to get env variables?

* Try to be less verbose

* Try to keep env variables

* Log into Docker

* Debug

* Forgot to re-add env vars

* No need for this env var

* Test login without sudo

* Preserve env for sudo

Co-authored-by: Pierre-Yves Lochou <pylochou@fr.ibm.com>

* Update build-and-test.yml

* Update Chart.yaml

* Update values.yaml

* Deliver 22.0.1 Release

* Release 22.0.1

* Fix travis (#36)

* Update download-cv.sh

* Fix linter

* update to CV 2.7.0

Co-authored-by: cmosbach <c.mosbach@fr.ibm.com>
Co-authored-by: Julie Garrone <47252804+julie-garrone@users.noreply.github.com>
Co-authored-by: Mathias Mouly <mathias.mouly@fr.ibm.com>
Co-authored-by: julie-garrone <julie.garrone@fr.ibm.om>
Co-authored-by: anthonyacremann <30266609+anthonyacremann@users.noreply.github.com>
Co-authored-by: Pierre-Yves Lochou <pylochou@fr.ibm.com>